//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @charset &apos;utf-8&apos;;
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Regular.ttf); }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Italic.ttf); font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold-Italic.ttf); font-weight: bold; font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold.ttf); font-weight: bold; }
        ///
        ///*{font-family:&quot;&lt;FONT&gt;&quot;, sans-serif;}
        ///h1{text-align:center;}
        ///h2{text-align:center;}
        ///h3{text-align:center;}
        ///img{max-width:100%;height:auto;display:block;ma [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Century Gothic.
        /// </summary>
        internal static string loading_fonts {
            get {
                return ResourceManager.GetString("loading_fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnify_icon_black {
            get {
                object obj = ResourceManager.GetObject("magnify_icon_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] malgun {
            get {
                object obj = ResourceManager.GetObject("malgun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @charset &apos;utf-8&apos;;
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Regular.ttf); }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Italic.ttf); font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold-Italic.ttf); font-weight: bold; font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold.ttf); font-weight: bold; }
        ///
        ///*{font-family:&quot;&lt;FONT&gt;&quot;, sans-serif;}
        ///body, html{height:100%;}
        ///h1{text-align:center;}
        ///h2{text-align:center;}
        ///h3{text-align:center;}
        ///img{max-width:100%;he [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Theme__default {
            get {
                return ResourceManager.GetString("Theme/_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @charset &apos;utf-8&apos;;
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Regular.ttf); }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Italic.ttf); font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold-Italic.ttf); font-weight: bold; font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold.ttf); font-weight: bold; }
        ///
        ///*{font-family:&quot;&lt;FONT&gt;&quot;, sans-serif;background:#FFE0AA;color:#666666;}
        ///body, html{height:100%;background:#FFE0AA;}
        ///h1{text-align:center;}
        ///h2{text-align:cen [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Theme_cream {
            get {
                return ResourceManager.GetString("Theme/cream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @charset &apos;utf-8&apos;;
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Regular.ttf); }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Italic.ttf); font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold-Italic.ttf); font-weight: bold; font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold.ttf); font-weight: bold; }
        ///
        ///*{font-family:&quot;&lt;FONT&gt;&quot;, sans-serif;background:#444444;color:#ffffff;}
        ///body, html{height:100%;background:#444444;}
        ///h1{text-align:center;}
        ///h2{text-align:cen [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Theme_dark {
            get {
                return ResourceManager.GetString("Theme/dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @charset &apos;utf-8&apos;;
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Regular.ttf); }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Italic.ttf); font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold-Italic.ttf); font-weight: bold; font-style: italic; }
        ///
        ///@font-face { font-family: &quot;&lt;FONT&gt;&quot;; src: url(Bold.ttf); font-weight: bold; }
        ///
        ///*{font-family:&quot;&lt;FONT&gt;&quot;, sans-serif;background:#444444;color:#ffffff;}
        ///body, html{background:#444444;height:100%;}
        ///h1{text-align:center;}
        ///h2{text-align:cen [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Theme_dark2 {
            get {
                return ResourceManager.GetString("Theme/dark2", resourceCulture);
            }
        }
    }
}
